MAINNET_TOKENLIST=`cat dist/mainnet.tokenlist.json`
GOERLI_TOKENLIST=`cat dist/goerli.tokenlist.json`

# Create the index file and populate it with the tokenlists
echo "
/** 
 * THIS FILE IS AUTO-GENERATED.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * See scripts/build-index.sh for details.
 */

import { TokenList } from '@uniswap/token-lists';
export * from './tags';

export const mainnetTokenList: TokenList = $MAINNET_TOKENLIST;
export const goerliTokenList: TokenList = $GOERLI_TOKENLIST;
" > src/index.ts

# Append the types.ts info here
cat src/tags.ts >> src/index.ts

tsc --project tsconfig.json